<?php
/**
 * @author Kitetop <1363215999@qq.com>
 * @version Release: 0.1
 * Date: 2018/10/5
 */

namespace App\Action;
use Kite\Action\BaseAction;

/**
 * 测试Action类
 * Class index
 * @package App\Action
 */
class Index extends BaseAction
{
    public function execute()
    {
        parent::execute(); // TODO: Change the autogenerated stub
    }
}